FROM bitnami/spark:3.5.0
WORKDIR /app
COPY spark_streaming.py .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0", "spark_streaming.py"]