FROM python:3.9-slim
WORKDIR /app
RUN pip install streamlit websockets plotly websocket-client altair
COPY dashboardFinal.py .
CMD ["streamlit", "run", "dashboardFinal.py", "--server.port=8501", "--server.address=0.0.0.0"]