FROM python:3.9-slim
WORKDIR /app
RUN pip install streamlit websockets plotly websocket-client altair
COPY dashboard.py .
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]